/**
 * Created by mitsuo.yamazaki on 14/02/07.
 */
    define(function() {

var test_case_json =
    [
        {"key" : "01", "exeflg" : true, "val": [
            "ConnectionType", "WiFiGetStatus", "FinishFinish"
        ], "WebView":1}


       /*
        {"key" : "01", "exeflg" : true, "val": [
            "ConnectionType", "ContactClone", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryMoveTo", "FileEntryToURL", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiOn", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundPlaySE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenShow", "VideoPlay", "FinishFinish"
        ], "WebView":1},
        {"key" : "02", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemoveRecursively", "FileEntryToURL", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetStatus", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceLight", "GameSoundLoadSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "03", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryToURL", "FileEntryToURL", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundReleaseAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "04", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCopyTo", "FileEntryGetParent", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageClear", "WiFiOff", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "05", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemoveRecursively", "FileEntryMoveTo", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageGet", "WiFiGetStatus", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceLight", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "06", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseOpenDatabase", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryToURL", "FileEntryFile", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiConnect", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundLoadSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "07", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseOpenDatabase", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryMoveTo", "FileEntryMoveTo", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiGetSSIDList", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "08", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseOpenDatabase", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCopyTo", "FileEntryToURL", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceLight", "GameSoundReleaseAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "09", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemoveRecursively", "FileEntryMoveTo", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiConnect", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoPlay", "FinishFinish"
        ], "WebView":1},
        {"key" : "10", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetDirectory", "FileEntryMoveTo", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiConnect", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceLight", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "11", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseOpenDatabase", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCopyTo", "FileEntryCopyTo", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiOn", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceLight", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "12", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseOpenDatabase", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetDirectory", "FileEntryFile", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenHide", "VideoPlay", "FinishFinish"
        ], "WebView":2},
        {"key" : "13", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemoveRecursively", "FileEntryCopyTo", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundReleaseAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "14", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCopyTo", "FileEntryFile", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageGet", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceLight", "GameSoundPlaySE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "15", "exeflg" : true, "val" : [
            "ConnectionType", "ContactClone", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemove", "FileEntryGetParent", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageClear", "WiFiOff", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceLight", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenHide", "VideoPlay", "FinishFinish"
        ], "WebView":1},
        {"key" : "16", "exeflg" : true, "val" : [
            "ConnectionType", "ContactCreate", "DatabaseOpenDatabase", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCreateReader", "FileEntryGetParent", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageClear", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceLight", "GameSoundReleaseAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoPlay", "FinishFinish"
        ], "WebView":1},
        {"key" : "17", "exeflg" : true, "val" : [
            "ConnectionType", "ContactCreate", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemove", "FileEntryToURL", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundLoadSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "18", "exeflg" : true, "val" : [
            "ConnectionType", "ContactCreate", "DatabaseOpenDatabase", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCopyTo", "FileEntryCopyTo", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetSSIDList", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "19", "exeflg" : true, "val" : [
            "ConnectionType", "ContactCreate", "DatabaseOpenDatabase", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemoveRecursively", "FileEntryToURL", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetSSIDList", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenHide", "VideoPlay", "FinishFinish"
        ], "WebView":2},
        {"key" : "20", "exeflg" : true, "val" : [
            "ConnectionType", "ContactCreate", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCreateReader", "FileEntryFile", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetStatus", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenHide", "VideoPlay", "FinishFinish"
        ], "WebView":1},
        {"key" : "21", "exeflg" : true, "val" : [
            "ConnectionType", "ContactCreate", "DatabaseOpenDatabase", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetDirectory", "FileEntryMoveTo", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageGet", "WiFiGetSSIDList", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundPlaySE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenShow", "VideoPlay", "FinishFinish"
        ], "WebView":2},
        {"key" : "22", "exeflg" : true, "val" : [
            "ConnectionType", "ContactCreate", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCopyTo", "FileEntryCopyTo", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiOn", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceLight", "GameSoundLoadSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "23", "exeflg" : true, "val" : [
            "ConnectionType", "ContactCreate", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemove", "FileEntryCopyTo", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageGet", "WiFiConnect", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundReleaseAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "24", "exeflg" : true, "val" : [
            "ConnectionType", "ContactCreate", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetParent", "FileEntryCopyTo", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageClear", "WiFiOff", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "25", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCreateReader", "FileEntryMoveTo", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageClear", "WiFiConnect", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceLight", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "26", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetDirectory", "FileEntryFile", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiGetSSIDList", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundLoadSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "27", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCopyTo", "FileEntryToURL", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageGet", "WiFiOff", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "28", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCopyTo", "FileEntryMoveTo", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetStatus", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceLight", "GameSoundReleaseAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "29", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetDirectory", "FileEntryFile", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageClear", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoPlay", "FinishFinish"
        ], "WebView":2},
        {"key" : "30", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryToURL", "FileEntryFile", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiGetStatus", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceLight", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "31", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemoveRecursively", "FileEntryCopyTo", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiConnect", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceLight", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "32", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseOpenDatabase", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCreateReader", "FileEntryFile", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiGetStatus", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenHide", "VideoPlay", "FinishFinish"
        ], "WebView":2},
        {"key" : "33", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetDirectory", "FileEntryToURL", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageClear", "WiFiConnect", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundReleaseAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "34", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetDirectory", "FileEntryToURL", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetSSIDList", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceLight", "GameSoundPlaySE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "35", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCreateReader", "FileEntryGetParent", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageClear", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceLight", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenHide", "VideoPlay", "FinishFinish"
        ], "WebView":2},
        {"key" : "36", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCopyTo", "FileEntryToURL", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceLight", "GameSoundReleaseAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoPlay", "FinishFinish"
        ], "WebView":1},
        {"key" : "37", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseOpenDatabase", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCreateReader", "FileEntryToURL", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageGet", "WiFiOff", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundLoadSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "38", "exeflg" : true, "val" : [
            "ConnectionType", "ContactFind", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetParent", "FileEntryMoveTo", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageGet", "WiFiOff", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "39", "exeflg" : true, "val" : [
            "ConnectionType", "ContactRemove", "DatabaseOpenDatabase", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCopyTo", "FileEntryFile", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiConnect", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenHide", "VideoPlay", "FinishFinish"
        ], "WebView":1},
        {"key" : "40", "exeflg" : true, "val" : [
            "ConnectionType", "ContactRemove", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryToURL", "FileEntryToURL", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenHide", "VideoPlay", "FinishFinish"
        ], "WebView":2},
        {"key" : "41", "exeflg" : true, "val" : [
            "ConnectionType", "ContactRemove", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryMoveTo", "FileEntryGetParent", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageClear", "WiFiConnect", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundPlaySE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenShow", "VideoPlay", "FinishFinish"
        ], "WebView":1},
        {"key" : "42", "exeflg" : true, "val" : [
            "ConnectionType", "ContactRemove", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetDirectory", "FileEntryGetParent", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiGetSSIDList", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceLight", "GameSoundLoadSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "43", "exeflg" : true, "val" : [
            "ConnectionType", "ContactRemove", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryMoveTo", "FileEntryCopyTo", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundReleaseAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "44", "exeflg" : true, "val" : [
            "ConnectionType", "ContactRemove", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemoveRecursively", "FileEntryToURL", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiGetStatus", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "45", "exeflg" : true, "val" : [
            "ConnectionType", "ContactRemove", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryToURL", "FileEntryCopyTo", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageClear", "WiFiOff", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceLight", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "46", "exeflg" : true, "val" : [
            "ConnectionType", "ContactRemove", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCreateReader", "FileEntryGetParent", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiOn", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundLoadSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "47", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemove", "FileEntryToURL", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "48", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemove", "FileEntryToURL", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageGet", "WiFiOff", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceLight", "GameSoundReleaseAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "49", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryToURL", "FileEntryGetParent", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetSSIDList", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoPlay", "FinishFinish"
        ], "WebView":1},
        {"key" : "50", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemove", "FileEntryCopyTo", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceLight", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "51", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryToURL", "FileEntryFile", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiGetSSIDList", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceLight", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "52", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCopyTo", "FileEntryGetParent", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenHide", "VideoPlay", "FinishFinish"
        ], "WebView":1},
        {"key" : "53", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseQuery", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetParent", "FileEntryToURL", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageRemove", "WiFiOn", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundReleaseAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "54", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseOpenDatabase", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCopyTo", "FileEntryCopyTo", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageGet", "WiFiOff", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceLight", "GameSoundPlaySE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationSchedule", "NotificationVibrate", "SplashScreenHide", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "55", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetParent", "FileEntryFile", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageClear", "WiFiGetSSIDList", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceLight", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenHide", "VideoPlay", "FinishFinish"
        ], "WebView":2},
        {"key" : "56", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryCreateReader", "FileEntryFile", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageGet", "WiFiGetSSIDList", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureAudio", "CompassGetCurrentHeading", "DeviceLight", "GameSoundReleaseAllSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoPlay", "FinishFinish"
        ], "WebView":1},
        {"key" : "57", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetParent", "FileEntryGetParent", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageClear", "WiFiOn", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraGetPicture", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundLoadSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":2},
        {"key" : "58", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseExec", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetDirectory", "FileEntryMoveTo", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageSet", "WiFiOn", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackEvent", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenShow", "VideoStop", "FinishFinish"
        ], "WebView":1},
        {"key" : "59", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryGetDirectory", "FileEntryCopyTo", "GlobalizationGetPreferredLanguage", "HTTPGet", "NotificationAlert", "SimpleStorageGet", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureVideo", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundStopSE", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationCancel", "NotificationVibrate", "SplashScreenHide", "VideoPlay", "FinishFinish"
        ], "WebView":2},
        {"key" : "60", "exeflg" : true, "val" : [
            "ConnectionType", "ContactSave", "DatabaseExecTransaction", "DeviceGetPushToken", "DocomoLocationGetCurrentPosition", "DirectoryEntryRemoveRecursively", "FileEntryFile", "GlobalizationGetLocaleName", "HTTPGet", "NotificationAlert", "SimpleStorageClear", "WiFiGetCurrentSSID", "CameraCleanup", "AccelerometerGetCurrentAcceleration", "BarcodeCaptureBarcode", "CameraSaveToPhotoAlbum", "CaptureCaptureImage", "CompassGetCurrentHeading", "DeviceGetDisplayInfo", "GameSoundSetSEVolume", "GEOLocationGetCurrentPosition", "GoogleAnalyticsTrackView", "LocalNotificationAllCancel", "NotificationVibrate", "SplashScreenHide", "VideoPlay", "FinishFinish"
        ], "WebView":1}
        */
    ];

        return {
            test_case_list : test_case_json
        };
    });
